// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhereIsOurCar;
using WhereIsOurCar.Car.Entity;

#nullable disable

namespace WhereIsOurCar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230420200550_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "car_user_kind", new[] { "owner", "regular" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhereIsOurCar.Car.Entity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("licence_plate");

                    b.HasKey("Id")
                        .HasName("pk_car");

                    b.ToTable("car", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.Car.Entity.CarUser", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<CarUserKind>("CarUserKind")
                        .HasColumnType("car_user_kind")
                        .HasColumnName("car_user_kind");

                    b.HasKey("CarId", "UserId")
                        .HasName("pk_car_x_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_car_x_user_user_id");

                    b.ToTable("car_x_user", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.File.Entity.S3File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("ServiceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_url");

                    b.HasKey("Id")
                        .HasName("pk_s3_file");

                    b.ToTable("s3_file", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.Photo.Entity.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FullId")
                        .HasColumnType("integer")
                        .HasColumnName("full_id");

                    b.Property<int>("ThumbId")
                        .HasColumnType("integer")
                        .HasColumnName("thumb_id");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("FullId")
                        .HasDatabaseName("ix_photos_full_id");

                    b.HasIndex("ThumbId")
                        .HasDatabaseName("ix_photos_thumb_id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.PositionHistory.Entity.PositionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("location");

                    b.Property<int>("ParkedById")
                        .HasColumnType("integer")
                        .HasColumnName("parked_by_id");

                    b.HasKey("Id")
                        .HasName("pk_position_history");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_position_history_car_id");

                    b.HasIndex("ParkedById")
                        .HasDatabaseName("ix_position_history_parked_by_id");

                    b.ToTable("position_history", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.PositionHistory.Entity.PositionHistoryPhoto", b =>
                {
                    b.Property<int>("PositionHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("position_history_id");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.HasKey("PositionHistoryId", "PhotoId")
                        .HasName("pk_position_history_x_photo");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_position_history_x_photo_photo_id");

                    b.ToTable("position_history_x_photo", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.User.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WhereIsOurCar.Car.Entity.CarUser", b =>
                {
                    b.HasOne("WhereIsOurCar.Car.Entity.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_x_user_car_car_id");

                    b.HasOne("WhereIsOurCar.User.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_x_user_user_user_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhereIsOurCar.Photo.Entity.Photo", b =>
                {
                    b.HasOne("WhereIsOurCar.File.Entity.S3File", "Full")
                        .WithMany()
                        .HasForeignKey("FullId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_s3_file_full_id");

                    b.HasOne("WhereIsOurCar.File.Entity.S3File", "Thumb")
                        .WithMany()
                        .HasForeignKey("ThumbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_s3_file_thumb_id");

                    b.Navigation("Full");

                    b.Navigation("Thumb");
                });

            modelBuilder.Entity("WhereIsOurCar.PositionHistory.Entity.PositionHistory", b =>
                {
                    b.HasOne("WhereIsOurCar.Car.Entity.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_history_car_car_id");

                    b.HasOne("WhereIsOurCar.User.Entity.User", "ParkedBy")
                        .WithMany()
                        .HasForeignKey("ParkedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_history_user_parked_by_id");

                    b.Navigation("Car");

                    b.Navigation("ParkedBy");
                });

            modelBuilder.Entity("WhereIsOurCar.PositionHistory.Entity.PositionHistoryPhoto", b =>
                {
                    b.HasOne("WhereIsOurCar.Photo.Entity.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_history_x_photo_photos_photo_id");

                    b.HasOne("WhereIsOurCar.PositionHistory.Entity.PositionHistory", "PositionHistory")
                        .WithMany("Photos")
                        .HasForeignKey("PositionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_history_x_photo_position_history_position_history_");

                    b.Navigation("Photo");

                    b.Navigation("PositionHistory");
                });

            modelBuilder.Entity("WhereIsOurCar.PositionHistory.Entity.PositionHistory", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
